    
def find_disease(number):
    disease_mapping = {
        "0": "(Vertigo) Paroymsal  Positional Vertigo",
        "1": "Abdominal Aortic Aneurysm",
        "2": "Acanthosis Nigricans",
        "3": "Achalasia",
        "4": "Achilles Tendinitis",
        "5": "Achilles Tendon Rupture",
        "6": "Acl Injury",
        "7": "Acne",
        "8": "Acoustic Neuroma",
        "9": "Acromegaly",
        "10": "Actinic Keratosis",
        "11": "Acute Coronary Syndrome",
        "12": "Acute Flaccid Myelitis",
        "13": "Acute Liver Failure",
        "14": "Acute Lymphocytic Leukemia",
        "15": "Acute Myelogenous Leukemia",
        "16": "Acute Sinusitis",
        "17": "Addisons Disease",
        "18": "Adenomyosis",
        "19": "Adhd",
        "20": "Adjustment Disorders",
        "21": "Adrenal Cancer",
        "22": "Adult Adhd",
        "23": "Adult Congenital Heart Disease",
        "24": "Adult Stills Disease",
        "25": "Age Spots",
        "26": "Agoraphobia",
        "27": "Aids",
        "28": "Airplane Ear",
        "29": "Albinism",
        "30": "Alcohol Intolerance",
        "31": "Alcohol Poisoning",
        "32": "Alcohol Use Disorder",
        "33": "Alcoholic Hepatitis",
        "34": "Allergies",
        "35": "Allergy",
        "36": "Alpha Gal Syndrome",
        "37": "Alzheimers Disease",
        "38": "Ambiguous Genitalia",
        "39": "Ameloblastoma",
        "40": "Amenorrhea",
        "41": "Amnesia",
        "42": "Ampullary Cancer",
        "43": "Amyloidosis",
        "44": "Amyotrophic Lateral Sclerosis",
        "45": "Anal Cancer",
        "46": "Anal Fissure",
        "47": "Anal Fistula",
        "48": "Anal Itching",
        "49": "Anaphylaxis",
        "50": "Anemia",
        "51": "Angelman Syndrome",
        "52": "Angina",
        "53": "Angiosarcoma",
        "54": "Ankylosing Spondylitis",
        "55": "Anorexia Nervosa",
        "56": "Anorgasmia",
        "57": "Anthrax",
        "58": "Antibiotic Associated Diarrhea",
        "59": "Antiphospholipid Syndrome",
        "60": "Antisocial Personality Disorder",
        "61": "Anxiety",
        "62": "Aortic Dissection",
        "63": "Aortic Stenosis",
        "64": "Aortic Valve Disease",
        "65": "Aortic Valve Regurgitation",
        "66": "Aphasia",
        "67": "Aplastic Anemia",
        "68": "Appendicitis",
        "69": "Arteriosclerosis Atherosclerosis",
        "70": "Arteriovenous Fistula",
        "71": "Arteriovenous Malformation",
        "72": "Arthritis",
        "73": "Asbestosis",
        "74": "Ascariasis",
        "75": "Aspergillosis",
        "76": "Asthma",
        "77": "Asthma Attack",
        "78": "Astigmatism",
        "79": "Ataxia",
        "80": "Atelectasis",
        "81": "Athletes Foot",
        "82": "Atopic Dermatitis Eczema",
        "83": "Atrial Fibrillation",
        "84": "Atrial Septal Defect",
        "85": "Atrioventricular Canal Defect",
        "86": "Atypical Hyperplasia",
        "87": "Autism Spectrum Disorder",
        "88": "Autoimmune Hepatitis",
        "89": "Autoimmune Pancreatitis",
        "90": "Autonomic Neuropathy",
        "91": "Avascular Necrosis",
        "92": "Baby Acne",
        "93": "Back Pain",
        "94": "Bacterial Vaginosis",
        "95": "Bad Breath",
        "96": "Bags Under Eyes",
        "97": "Bakers Cyst",
        "98": "Balance Problems",
        "99": "Barretts Esophagus",
        "100": "Bartholin Cyst",
        "101": "Basal Cell Carcinoma",
        "102": "Bed Sores",
        "103": "Bed Wetting",
        "104": "Bedbugs",
        "105": "Bee Stings",
        "106": "Behcets Disease",
        "107": "Bells Palsy",
        "108": "Benign Prostatic Hyperplasia",
        "109": "Bile Reflux",
        "110": "Binge Eating Disorder",
        "111": "Bipolar Disorder",
        "112": "Black Hairy Tongue",
        "113": "Bladder Cancer",
        "114": "Bladder Exstrophy",
        "115": "Bladder Stones",
        "116": "Blastocystis Hominis Infection",
        "117": "Blepharitis",
        "118": "Blocked Tear Duct",
        "119": "Blood In Urine",
        "120": "Body Dysmorphic Disorder",
        "121": "Body Lice",
        "122": "Boils And Carbuncles",
        "123": "Bone And Joint Infections",
        "124": "Bone Cancer",
        "125": "Bone Metastasis",
        "126": "Bone Spurs",
        "127": "Borderline Personality Disorder",
        "128": "Botulism",
        "129": "Brachial Plexus Injury",
        "130": "Bradycardia",
        "131": "Brain Aneurysm",
        "132": "Brain Avm",
        "133": "Brain Metastases",
        "134": "Brain Tumor",
        "135": "Breast Cancer",
        "136": "Breast Cysts",
        "137": "Breast Pain",
        "138": "Broken Ankle",
        "139": "Broken Arm",
        "140": "Broken Collarbone",
        "141": "Broken Foot",
        "142": "Broken Hand",
        "143": "Broken Heart Syndrome",
        "144": "Broken Leg",
        "145": "Broken Nose",
        "146": "Broken Ribs",
        "147": "Broken Toe",
        "148": "Broken Wrist",
        "149": "Bronchial Asthma",
        "150": "Bronchiolitis",
        "151": "Bronchitis",
        "152": "Brucellosis",
        "153": "Brugada Syndrome",
        "154": "Bruxism",
        "155": "Buergers Disease",
        "156": "Bulimia",
        "157": "Bullous Pemphigoid",
        "158": "Bundle Branch Block",
        "159": "Bunions",
        "160": "Burning Mouth Syndrome",
        "161": "Burns",
        "162": "Bursitis",
        "163": "C Difficile",
        "164": "Calciphylaxis",
        "165": "Cancer",
        "166": "Canker Sore",
        "167": "Carbon Monoxide",
        "168": "Carcinoid Syndrome",
        "169": "Carcinoid Tumors",
        "170": "Carcinoma Unknown Primary",
        "171": "Cardiogenic Shock",
        "172": "Cardiomyopathy",
        "173": "Carotid Artery Disease",
        "174": "Carpal Tunnel Syndrome",
        "175": "Castleman Disease",
        "176": "Cataracts",
        "177": "Cavernous Malformations",
        "178": "Cavities",
        "179": "Celiac Disease",
        "180": "Cellulite",
        "181": "Cellulitis",
        "182": "Central Sleep Apnea",
        "183": "Cerebral Palsy",
        "184": "Cervical Cancer",
        "185": "Cervical Dystonia",
        "186": "Cervical Spondylosis",
        "187": "Cervicitis",
        "188": "Chagas Disease",
        "189": "Charcot Marie Tooth Disease",
        "190": "Chemo Brain",
        "191": "Chest Pain",
        "192": "Chiari Malformation",
        "193": "Chicken Pox",
        "194": "Chickenpox",
        "195": "Chilblains",
        "196": "Child Abuse",
        "197": "Childhood Apraxia Of Speech",
        "198": "Childhood Asthma",
        "199": "Childhood Obesity",
        "200": "Childhood Schizophrenia",
        "201": "Chlamydia",
        "202": "Cholangiocarcinoma",
        "203": "Cholecystitis",
        "204": "Cholera",
        "205": "Cholestasis Of Pregnancy",
        "206": "Chondrosarcoma",
        "207": "Chronic Cholestasis",
        "208": "Chronic Cough",
        "209": "Chronic Daily Headaches",
        "210": "Chronic Exertional Compartment Syndrome",
        "211": "Chronic Fatigue Syndrome",
        "212": "Chronic Granulomatous Disease",
        "213": "Chronic Hives",
        "214": "Chronic Kidney Disease",
        "215": "Chronic Lymphocytic Leukemia",
        "216": "Chronic Myelogenous Leukemia",
        "217": "Chronic Pelvic Pain",
        "218": "Chronic Sinusitis",
        "219": "Chronic Traumatic Encephalopathy",
        "220": "Churg Strauss Syndrome",
        "221": "Cirrhosis",
        "222": "Claudication",
        "223": "Cleft Palate",
        "224": "Clubfoot",
        "225": "Cluster Headache",
        "226": "Cmv",
        "227": "Coarctation Of The Aorta",
        "228": "Cold Sore",
        "229": "Cold Urticaria",
        "230": "Colic",
        "231": "Colon Cancer",
        "232": "Colon Polyps",
        "233": "Coma",
        "234": "Common Cold",
        "235": "Common Cold In Babies",
        "236": "Common Variable Immunodeficiency",
        "237": "Common Warts",
        "238": "Complicated Grief",
        "239": "Concussion",
        "240": "Congenital Adrenal Hyperplasia",
        "241": "Congenital Diaphragmatic Hernia",
        "242": "Congenital Heart Defects Children",
        "243": "Conjoined Twins",
        "244": "Constipation",
        "245": "Constipation In Children",
        "246": "Contact Dermatitis",
        "247": "Conversion Disorder",
        "248": "Copd",
        "249": "Coronary Artery Disease",
        "250": "Corticobasal Degeneration",
        "251": "Costochondritis",
        "252": "Cradle Cap",
        "253": "Craniosynostosis",
        "254": "Creutzfeldt Jakob Disease",
        "255": "Crohns Disease",
        "256": "Croup",
        "257": "Crps Complex Regional Pain Syndrome",
        "258": "Cryoglobulinemia",
        "259": "Csf Leak",
        "260": "Cushing Syndrome",
        "261": "Cutaneous T Cell Lymphoma",
        "262": "Cyclic Vomiting Syndrome",
        "263": "Cyclothymia",
        "264": "Cystic Fibrosis",
        "265": "Cystitis",
        "266": "Cystocele",
        "267": "Dandruff",
        "268": "Dcis",
        "269": "De Quervain Tenosynovitis",
        "270": "Deep Vein Thrombosis",
        "271": "Dehydration",
        "272": "Delayed Ejaculation",
        "273": "Delirium",
        "274": "Dementia",
        "275": "Dengue",
        "276": "Dengue Fever",
        "277": "Depersonalization Derealization Disorder",
        "278": "Depression",
        "279": "Dermatitis Eczema",
        "280": "Dermatographia",
        "281": "Dermatomyositis",
        "282": "Desmoid Tumors",
        "283": "Deviated Septum",
        "284": "Diabetes",
        "285": "Diabetes ",
        "286": "Diabetes Insipidus",
        "287": "Diabetic Coma",
        "288": "Diabetic Hypoglycemia",
        "289": "Diabetic Ketoacidosis",
        "290": "Diabetic Nephropathy",
        "291": "Diabetic Neuropathy",
        "292": "Diabetic Retinopathy",
        "293": "Diaper Rash",
        "294": "Diarrhea",
        "295": "Digeorge Syndrome",
        "296": "Dilated Cardiomyopathy",
        "297": "Dimorphic Hemmorhoids(Piles)",
        "298": "Diphtheria",
        "299": "Dislocated Shoulder",
        "300": "Dissociative Disorders",
        "301": "Diverticulitis",
        "302": "Dizziness",
        "303": "Double Uterus",
        "304": "Down Syndrome",
        "305": "Dresslers Syndrome",
        "306": "Drug Addiction",
        "307": "Drug Allergy",
        "308": "Drug Reaction",
        "309": "Dry Eyes",
        "310": "Dry Macular Degeneration",
        "311": "Dry Mouth",
        "312": "Dry Skin",
        "313": "Dry Socket",
        "314": "Dsrct",
        "315": "Dumping Syndrome",
        "316": "Dupuytrens Contracture",
        "317": "Dural Arteriovenous Fistulas",
        "318": "Dust Mites",
        "319": "Dwarfism",
        "320": "Dysarthria",
        "321": "Dyshidrosis",
        "322": "Dyslexia",
        "323": "Dysphagia",
        "324": "Dystonia",
        "325": "E Coli",
        "326": "Ear Infections",
        "327": "Eating Disorders",
        "328": "Ebsteins Anomaly",
        "329": "Ectopic Pregnancy",
        "330": "Ectropion",
        "331": "Edema",
        "332": "Egg Allergy",
        "333": "Ehlers Danlos Syndrome",
        "334": "Ehrlichiosis",
        "335": "Eisenmenger Syndrome",
        "336": "Emphysema",
        "337": "Encephalitis",
        "338": "Encopresis",
        "339": "End Stage Renal Disease",
        "340": "Endocarditis",
        "341": "Endometriosis",
        "342": "Enlarged Liver",
        "343": "Enlarged Spleen",
        "344": "Enterocele",
        "345": "Entropion",
        "346": "Eosinophilic Esophagitis",
        "347": "Epidermoid Cysts",
        "348": "Epidermolysis Bullosa",
        "349": "Epididymitis",
        "350": "Epilepsy",
        "351": "Erectile Dysfunction",
        "352": "Esophageal Cancer",
        "353": "Esophageal Spasms",
        "354": "Esophageal Varices",
        "355": "Esophagitis",
        "356": "Essential Tremor",
        "357": "Esthesioneuroblastoma",
        "358": "Ewing Sarcoma",
        "359": "Exercise Headaches",
        "360": "Exercise Induced Asthma",
        "361": "Eye Floaters",
        "362": "Eye Melanoma",
        "363": "Eyestrain",
        "364": "Factitious Disorder",
        "365": "Factor V Leiden",
        "366": "Familial Adenomatous Polyposis",
        "367": "Familial Hypercholesterolemia",
        "368": "Familial Mediterranean Fever",
        "369": "Farsightedness",
        "370": "Febrile Seizure",
        "371": "Fecal Incontinence",
        "372": "Female Infertility",
        "373": "Female Sexual Dysfunction",
        "374": "Fetal Alcohol Syndrome",
        "375": "Fetal Macrosomia",
        "376": "Fever",
        "377": "Fibroadenoma",
        "378": "Fibrocystic Breasts",
        "379": "Fibromuscular Dysplasia",
        "380": "Fibromyalgia",
        "381": "Flatfeet",
        "382": "Floor Mouth Cancer",
        "383": "Flu",
        "384": "Folliculitis",
        "385": "Food Allergy",
        "386": "Food Poisoning",
        "387": "Foot Drop",
        "388": "Frontal Lobe Seizures",
        "389": "Frontotemporal Dementia",
        "390": "Frostbite",
        "391": "Frozen Shoulder",
        "392": "Fuchs Dystrophy",
        "393": "Functional Dyspepsia",
        "394": "Fungal Infection",
        "395": "Galactorrhea",
        "396": "Gallbladder Cancer",
        "397": "Gallstones",
        "398": "Ganglion Cyst",
        "399": "Gangrene",
        "400": "Gas And Gas Pains",
        "401": "Gastritis",
        "402": "Gastroenteritis",
        "403": "Gastroesophageal Reflux Disease",
        "404": "Gastrointestinal Bleeding",
        "405": "Gastroparesis",
        "406": "Gauchers Disease",
        "407": "Gender Dysphoria",
        "408": "Generalized Anxiety Disorder",
        "409": "Genital Herpes",
        "410": "Genital Warts",
        "411": "Geographic Tongue",
        "412": "Gerd",
        "413": "Gestational Diabetes",
        "414": "Giant Cell Arteritis",
        "415": "Giardia Infection",
        "416": "Gilberts Syndrome",
        "417": "Gingivitis",
        "418": "Glaucoma",
        "419": "Glioma",
        "420": "Glomerulonephritis",
        "421": "Goiter",
        "422": "Golfers Elbow",
        "423": "Gonorrhea",
        "424": "Gout",
        "425": "Grand Mal Seizure",
        "426": "Granuloma Annulare",
        "427": "Granulomatosis With Polyangiitis",
        "428": "Graves Disease",
        "429": "Greenstick Fractures",
        "430": "Group B Strep",
        "431": "Growth Plate Fractures",
        "432": "Guillain Barre Syndrome",
        "433": "Gynecomastia",
        "434": "H Pylori",
        "435": "Hair Loss",
        "436": "Hairy Cell Leukemia",
        "437": "Hammertoe And Mallet Toe",
        "438": "Hamstring Injury",
        "439": "Hand Foot And Mouth Disease",
        "440": "Hangovers",
        "441": "Hantavirus Pulmonary Syndrome",
        "442": "Hay Fever",
        "443": "Head Lice",
        "444": "Headaches In Children",
        "445": "Hearing Loss",
        "446": "Heart Arrhythmia",
        "447": "Heart Attack",
        "448": "Heart Disease",
        "449": "Heart Failure",
        "450": "Heart Murmurs",
        "451": "Heart Palpitations",
        "452": "Heart Valve Disease",
        "453": "Heartburn",
        "454": "Heat Exhaustion",
        "455": "Heat Rash",
        "456": "Heat Stroke",
        "457": "Hemangioma",
        "458": "Hemifacial Spasm",
        "459": "Hemochromatosis",
        "460": "Hemolytic Uremic Syndrome",
        "461": "Hemophilia",
        "462": "Hemorrhoids",
        "463": "Henoch Schonlein Purpura",
        "464": "Hepatitis A",
        "465": "Hepatitis B",
        "466": "Hepatitis C",
        "467": "Hepatitis D",
        "468": "Hepatitis E",
        "469": "Hepatopulmonary Syndrome",
        "470": "Herniated Disk",
        "471": "Hht",
        "472": "Hiatal Hernia",
        "473": "Hiccups",
        "474": "Hidradenitis Suppurativa",
        "475": "High Blood Cholesterol",
        "476": "High Blood Pressure",
        "477": "High Blood Pressure In Children",
        "478": "Hip Dysplasia",
        "479": "Hip Fracture",
        "480": "Hip Labral Tear",
        "481": "Hirschsprungs Disease",
        "482": "Histoplasmosis",
        "483": "Hiv Aids",
        "484": "Hives And Angioedema",
        "485": "Hoarding Disorder",
        "486": "Hodgkins Lymphoma",
        "487": "Horner Syndrome",
        "488": "Hot Flashes",
        "489": "Hpv Infection",
        "490": "Huntingtons Disease",
        "491": "Hurthle Cell Cancer",
        "492": "Hydrocele",
        "493": "Hydrocephalus",
        "494": "Hypercalcemia",
        "495": "Hypereosinophilic Syndrome",
        "496": "Hyperglycemia",
        "497": "Hyperhidrosis",
        "498": "Hyperoxaluria",
        "499": "Hyperparathyroidism",
        "500": "Hypertension",
        "501": "Hypertension ",
        "502": "Hyperthyroidism",
        "503": "Hypertrophic Cardiomyopathy",
        "504": "Hypoglycemia",
        "505": "Hyponatremia",
        "506": "Hypoparathyroidism",
        "507": "Hypopituitarism",
        "508": "Hypoplastic Left Heart Syndrome",
        "509": "Hypospadias",
        "510": "Hypothermia",
        "511": "Hypothyroidism",
        "512": "Idiopathic Thrombocytopenic Purpura",
        "513": "Iga Nephropathy",
        "514": "Illness Anxiety Disorder",
        "515": "Impetigo",
        "516": "Incompetent Cervix",
        "517": "Indigestion",
        "518": "Infant Acid Reflux",
        "519": "Infant Jaundice",
        "520": "Infectious Diseases",
        "521": "Infertility",
        "522": "Inflammatory Bowel Disease",
        "523": "Inflammatory Breast Cancer",
        "524": "Ingrown Hair",
        "525": "Ingrown Toenails",
        "526": "Inguinal Hernia",
        "527": "Insomnia",
        "528": "Intermittent Explosive Disorder",
        "529": "Interstitial Cystitis",
        "530": "Interstitial Lung Disease",
        "531": "Intestinal Ischemia",
        "532": "Intestinal Obstruction",
        "533": "Intracranial Hematoma",
        "534": "Intussusception",
        "535": "Invasive Lobular Carcinoma",
        "536": "Iritis",
        "537": "Iron Deficiency Anemia",
        "538": "Irritable Bowel Syndrome",
        "539": "Ischemic Colitis",
        "540": "Itchy Skin",
        "541": "Jaundice",
        "542": "Jaw Tumors Cysts",
        "543": "Jellyfish Stings",
        "544": "Jet Lag",
        "545": "Jock Itch",
        "546": "Juvenile Idiopathic Arthritis",
        "547": "Kawasaki Disease",
        "548": "Keloid Scar",
        "549": "Keratitis",
        "550": "Keratoconus",
        "551": "Keratosis Pilaris",
        "552": "Kidney Cancer",
        "553": "Kidney Cysts",
        "554": "Kidney Failure",
        "555": "Kidney Infection",
        "556": "Kidney Stones",
        "557": "Kleptomania",
        "558": "Klinefelter Syndrome",
        "559": "Klippel Trenaunay",
        "560": "Knee Bursitis",
        "561": "Knee Pain",
        "562": "Kyphosis",
        "563": "Lactose Intolerance",
        "564": "Laryngitis",
        "565": "Latex Allergy",
        "566": "Lazy Eye",
        "567": "Lead Poisoning",
        "568": "Left Ventricular Hypertrophy",
        "569": "Legg Calve Perthes Disease",
        "570": "Legionnaires Disease",
        "571": "Leukemia",
        "572": "Leukoplakia",
        "573": "Lewy Body Dementia",
        "574": "Lice",
        "575": "Lichen Planus",
        "576": "Lichen Sclerosus",
        "577": "Lip Cancer",
        "578": "Lipoma",
        "579": "Liposarcoma",
        "580": "Listeria Infection",
        "581": "Liver Cancer",
        "582": "Liver Hemangioma",
        "583": "Liver Problems",
        "584": "Lobular Carcinoma In Situ",
        "585": "Long Qt Syndrome",
        "586": "Low Blood Pressure",
        "587": "Low Sex Drive In Women",
        "588": "Low Sperm Count",
        "589": "Lung Cancer",
        "590": "Lupus",
        "591": "Lupus Nephritis",
        "592": "Lyme Disease",
        "593": "Lymphedema",
        "594": "Lymphoma",
        "595": "Lynch Syndrome",
        "596": "Malaria",
        "597": "Male Breast Cancer",
        "598": "Male Hypogonadism",
        "599": "Male Infertility",
        "600": "Malignant Hyperthermia",
        "601": "Malignant Peripheral Nerve Sheath Tumors",
        "602": "Mammary Duct Ectasia",
        "603": "Marfan Syndrome",
        "604": "Mastitis",
        "605": "Mcad Deficiency",
        "606": "Measles",
        "607": "Median Arcuate Ligament Syndrome Mals",
        "608": "Medication Overuse Headache",
        "609": "Melanoma",
        "610": "Men 1",
        "611": "Men 2",
        "612": "Menieres Disease",
        "613": "Meningioma",
        "614": "Meningitis",
        "615": "Menopause",
        "616": "Menorrhagia",
        "617": "Menstrual Cramps",
        "618": "Mental Illness",
        "619": "Meralgia Paresthetica",
        "620": "Merkel Cell Carcinoma",
        "621": "Mesenteric Ischemia",
        "622": "Mesenteric Lymphadenitis",
        "623": "Mesothelioma",
        "624": "Metabolic Syndrome",
        "625": "Metachromatic Leukodystrophy",
        "626": "Metatarsalgia",
        "627": "Mgus",
        "628": "Microcephaly",
        "629": "Microscopic Colitis",
        "630": "Migraine",
        "631": "Migraine Headache",
        "632": "Migraine With Aura",
        "633": "Mild Cognitive Impairment",
        "634": "Milk Allergy",
        "635": "Mitral Valve Disease",
        "636": "Mitral Valve Prolapse",
        "637": "Mitral Valve Regurgitation",
        "638": "Mitral Valve Stenosis",
        "639": "Mittelschmerz",
        "640": "Mixed Connective Tissue Disease",
        "641": "Molar Pregnancy",
        "642": "Mold Allergy",
        "643": "Moles",
        "644": "Molluscum Contagiosum",
        "645": "Mononucleosis",
        "646": "Morning Sickness",
        "647": "Morphea",
        "648": "Mortons Neuroma",
        "649": "Mosquito Bites",
        "650": "Mouth Cancer",
        "651": "Mrsa",
        "652": "Multiple Myeloma",
        "653": "Multiple Sclerosis",
        "654": "Multiple System Atrophy",
        "655": "Mumps",
        "656": "Muscle Cramp",
        "657": "Muscle Strains",
        "658": "Muscular Dystrophy",
        "659": "Myasthenia Gravis",
        "660": "Myelodysplastic Syndrome",
        "661": "Myelofibrosis",
        "662": "Myocardial Ischemia",
        "663": "Myocarditis",
        "664": "Myoclonus",
        "665": "Myofascial Pain Syndrome",
        "666": "Nail Fungus",
        "667": "Narcissistic Personality Disorder",
        "668": "Narcolepsy",
        "669": "Nasal Paranasal Tumors",
        "670": "Nasal Polyps",
        "671": "Nasopharyngeal Carcinoma",
        "672": "Nearsightedness",
        "673": "Neck Pain",
        "674": "Nephrogenic Systemic Fibrosis",
        "675": "Nephrotic Syndrome",
        "676": "Neuroblastoma",
        "677": "Neurodermatitis",
        "678": "Neuroendocrine Tumors",
        "679": "Neurofibromatosis",
        "680": "Nickel Allergy",
        "681": "Nicotine Dependence",
        "682": "Niemann Pick",
        "683": "Nightmare Disorder",
        "684": "Non Hodgkins Lymphoma",
        "685": "Nonalcoholic Fatty Liver Disease",
        "686": "Nonallergic Rhinitis",
        "687": "Noonan Syndrome",
        "688": "Norovirus",
        "689": "Obesity",
        "690": "Obsessive Compulsive Disorder",
        "691": "Obstructive Sleep Apnea",
        "692": "Occupational Asthma",
        "693": "Ocular Rosacea",
        "694": "Oppositional Defiant Disorder",
        "695": "Optic Neuritis",
        "696": "Oral Lichen Planus",
        "697": "Oral Thrush",
        "698": "Orchitis",
        "699": "Orthostatic Hypotension",
        "700": "Osteoarthristis",
        "701": "Osteoarthritis",
        "702": "Osteochondritis Dissecans",
        "703": "Osteomyelitis",
        "704": "Osteoporosis",
        "705": "Osteosarcoma",
        "706": "Ovarian Cancer",
        "707": "Ovarian Cysts",
        "708": "Ovarian Hyperstimulation Syndrome Ohss",
        "709": "Overactive Bladder",
        "710": "Pagets Disease Of Bone",
        "711": "Pagets Disease Of The Breast",
        "712": "Painful Intercourse",
        "713": "Pancreatic Cancer",
        "714": "Pancreatic Cysts",
        "715": "Pancreatic Neuroendocrine Tumors",
        "716": "Pancreatitis",
        "717": "Panic Attacks",
        "718": "Paralysis (Brain Hemorrhage)",
        "719": "Paraneoplastic Syndromes",
        "720": "Parkinsons Disease",
        "721": "Parvovirus Infection",
        "722": "Patellar Tendinitis",
        "723": "Patellofemoral Pain Syndrome",
        "724": "Patent Ductus Arteriosus",
        "725": "Patent Foramen Ovale",
        "726": "Pcos",
        "727": "Peanut Allergy",
        "728": "Pectus Excavatum",
        "729": "Pediatric Brain Tumor",
        "730": "Pediatric Sleep Apnea",
        "731": "Pelvic Inflammatory Disease",
        "732": "Pemphigus",
        "733": "Penicillin Allergy",
        "734": "Peptic Ulcer",
        "735": "Peptic Ulcer Diseae",
        "736": "Peptic Ulcer Disease",
        "737": "Pericardial Effusion",
        "738": "Pericarditis",
        "739": "Perimenopause",
        "740": "Periodontitis",
        "741": "Peripheral Artery Disease",
        "742": "Peripheral Nerve Injuries",
        "743": "Peripheral Nerve Tumors",
        "744": "Peripheral Nerve Tumors Benign",
        "745": "Peripheral Neuropathy",
        "746": "Peritonitis",
        "747": "Persistent Depressive Disorder",
        "748": "Personality Disorders",
        "749": "Pet Allergy",
        "750": "Petit Mal Seizure",
        "751": "Peyronies Disease",
        "752": "Phenylketonuria",
        "753": "Pheochromocytoma",
        "754": "Pilonidal Cyst",
        "755": "Pinched Nerve",
        "756": "Pink Eye",
        "757": "Pinworm",
        "758": "Pituitary Tumors",
        "759": "Pityriasis Rosea",
        "760": "Placenta Accreta",
        "761": "Placenta Previa",
        "762": "Placental Abruption",
        "763": "Plague",
        "764": "Plantar Fasciitis",
        "765": "Plantar Warts",
        "766": "Pneumonia",
        "767": "Pneumonitis",
        "768": "Pneumothorax",
        "769": "Poison Ivy",
        "770": "Polio",
        "771": "Polycystic Kidney Disease",
        "772": "Polycythemia Vera",
        "773": "Polyhydramnios",
        "774": "Polymorphous Light Eruption",
        "775": "Polymyalgia Rheumatica",
        "776": "Polymyositis",
        "777": "Poor Color Vision",
        "778": "Popliteal Artery Aneurysm",
        "779": "Popliteal Artery Entrapment",
        "780": "Porphyria",
        "781": "Post Concussion Syndrome",
        "782": "Post Polio Syndrome",
        "783": "Post Traumatic Stress Disorder",
        "784": "Post Vasectomy Pain Syndrome",
        "785": "Posterior Cortical Atrophy",
        "786": "Postherpetic Neuralgia",
        "787": "Postpartum Depression",
        "788": "Postpartum Preeclampsia",
        "789": "Pouchitis",
        "790": "Prader Willi Syndrome",
        "791": "Precocious Puberty",
        "792": "Prediabetes",
        "793": "Preeclampsia",
        "794": "Pregnancy Loss Miscarriage",
        "795": "Prehypertension",
        "796": "Premature Birth",
        "797": "Premature Ejaculation",
        "798": "Premature Ovarian Failure",
        "799": "Premature Ventricular Contractions",
        "800": "Premenstrual Syndrome",
        "801": "Presbyopia",
        "802": "Prescription Drug Abuse",
        "803": "Preterm Labor",
        "804": "Priapism",
        "805": "Primary Biliary Cholangitis",
        "806": "Primary Cough Headaches",
        "807": "Primary Immunodeficiency",
        "808": "Primary Lateral Sclerosis",
        "809": "Primary Progressive Aphasia",
        "810": "Primary Sclerosing Cholangitis",
        "811": "Proctitis",
        "812": "Progeria",
        "813": "Progressive Supranuclear Palsy",
        "814": "Prolactinoma",
        "815": "Prostate Cancer",
        "816": "Prostatitis",
        "817": "Pseudobulbar Affect",
        "818": "Pseudocholinesterase Deficiency",
        "819": "Pseudogout",
        "820": "Pseudomembranous Colitis",
        "821": "Pseudotumor Cerebri",
        "822": "Psoriasis",
        "823": "Psoriatic Arthritis",
        "824": "Pubic Lice Crabs",
        "825": "Pulmonary Atresia",
        "826": "Pulmonary Edema",
        "827": "Pulmonary Embolism",
        "828": "Pulmonary Fibrosis",
        "829": "Pulmonary Hypertension",
        "830": "Pulmonary Valve Stenosis",
        "831": "Pyloric Stenosis",
        "832": "Pyoderma Gangrenosum",
        "833": "Rabies",
        "834": "Radiation Enteritis",
        "835": "Radiation Sickness",
        "836": "Ramsay Hunt Syndrome",
        "837": "Raynauds Disease",
        "838": "Reactive Arthritis",
        "839": "Reactive Attachment Disorder",
        "840": "Rectal Cancer",
        "841": "Rectal Prolapse",
        "842": "Rectal Ulcer",
        "843": "Rectocele",
        "844": "Rectovaginal Fistula",
        "845": "Recurrent Breast Cancer",
        "846": "Rem Sleep Behavior Disorder",
        "847": "Renal Artery Stenosis",
        "848": "Respiratory Syncytial Virus",
        "849": "Restless Legs Syndrome",
        "850": "Retinal Detachment",
        "851": "Retinal Diseases",
        "852": "Retinoblastoma",
        "853": "Retractile Testicle",
        "854": "Retrograde Ejaculation",
        "855": "Rett Syndrome",
        "856": "Reyes Syndrome",
        "857": "Rhabdomyosarcoma",
        "858": "Rheumatic Fever",
        "859": "Rheumatoid Arthritis",
        "860": "Rickets",
        "861": "Ringworm Body",
        "862": "Ringworm Scalp",
        "863": "Rosacea",
        "864": "Roseola",
        "865": "Rotator Cuff Injury",
        "866": "Rotavirus",
        "867": "Rubella",
        "868": "Rumination Syndrome",
        "869": "Ruptured Eardrum",
        "870": "Ruptured Spleen",
        "871": "Sacral Dimple",
        "872": "Sacroiliitis",
        "873": "Salivary Gland Cancer",
        "874": "Salmonella",
        "875": "Sarcoidosis",
        "876": "Sarcoma",
        "877": "Sars",
        "878": "Scabies",
        "879": "Scarlet Fever",
        "880": "Schizoaffective Disorder",
        "881": "Schizoid Personality Disorder",
        "882": "Schizophrenia",
        "883": "Schizotypal Personality Disorder",
        "884": "Sciatica",
        "885": "Scleroderma",
        "886": "Sclerosing Mesenteritis",
        "887": "Scoliosis",
        "888": "Scorpion Stings",
        "889": "Scrotal Masses",
        "890": "Seasonal Affective Disorder",
        "891": "Seborrheic Dermatitis",
        "892": "Seborrheic Keratosis",
        "893": "Secondary Hypertension",
        "894": "Seizure",
        "895": "Separation Anxiety Disorder",
        "896": "Sepsis",
        "897": "Serotonin Syndrome",
        "898": "Sex Headaches",
        "899": "Sexually Transmitted Diseases Stds",
        "900": "Shaken Baby Syndrome",
        "901": "Shellfish Allergy",
        "902": "Shigella",
        "903": "Shin Splints",
        "904": "Shingles",
        "905": "Short Bowel Syndrome",
        "906": "Sick Sinus Syndrome",
        "907": "Sickle Cell Anemia",
        "908": "Sinus Headaches",
        "909": "Sjogrens Syndrome",
        "910": "Skin Cancer",
        "911": "Sleep Apnea",
        "912": "Sleep Disorders",
        "913": "Sleep Terrors",
        "914": "Sleepwalking",
        "915": "Small Bowel Cancer",
        "916": "Small Intestinal Bacterial Overgrowth",
        "917": "Small Vessel Disease",
        "918": "Smallpox",
        "919": "Snoring",
        "920": "Social Anxiety Disorder",
        "921": "Soft Palate Cancer",
        "922": "Soft Tissue Sarcoma",
        "923": "Somatic Symptom Disorder",
        "924": "Sore Throat",
        "925": "Specific Phobias",
        "926": "Spermatocele",
        "927": "Spider Bites",
        "928": "Spina Bifida",
        "929": "Spinal Arteriovenous Malformation",
        "930": "Spinal Cord Injury",
        "931": "Spinal Cord Tumor",
        "932": "Spinal Headaches",
        "933": "Spinal Stenosis",
        "934": "Spontaneous Coronary Artery Dissection",
        "935": "Sprained Ankle",
        "936": "Sprains",
        "937": "Squamous Cell Carcinoma",
        "938": "Stage 4 Prostate Cancer",
        "939": "Staph Infections",
        "940": "Stevens Johnson Syndrome",
        "941": "Stickler Syndrome",
        "942": "Stomach Cancer",
        "943": "Stomach Polyps",
        "944": "Strep Throat",
        "945": "Stress Fractures",
        "946": "Stress Incontinence",
        "947": "Stretch Marks",
        "948": "Stroke",
        "949": "Stuttering",
        "950": "Sty",
        "951": "Subconjunctival Hemorrhage",
        "952": "Sudden Cardiac Arrest",
        "953": "Suicide",
        "954": "Sun Allergy",
        "955": "Sunburn",
        "956": "Supraventricular Tachycardia",
        "957": "Suspicious Breast Lumps",
        "958": "Sweating And Body Odor",
        "959": "Swimmers Ear",
        "960": "Swimmers Itch",
        "961": "Swine Flu",
        "962": "Swollen Knee",
        "963": "Swollen Lymph Nodes",
        "964": "Syphilis",
        "965": "Systemic Mastocytosis",
        "966": "Tachycardia",
        "967": "Takayasus Arteritis",
        "968": "Tapeworm",
        "969": "Tay Sachs Disease",
        "970": "Teen Depression",
        "971": "Temporal Lobe Seizure",
        "972": "Tendinitis",
        "973": "Tennis Elbow",
        "974": "Tension Headache",
        "975": "Testicular Cancer Care",
        "976": "Testicular Torsion",
        "977": "Tetanus",
        "978": "Tetralogy Of Fallot",
        "979": "Thalassemia",
        "980": "Thoracic Aortic Aneurysm",
        "981": "Thoracic Outlet Syndrome",
        "982": "Throat Cancer",
        "983": "Thrombocytopenia",
        "984": "Thrombocytosis",
        "985": "Thumb Arthritis",
        "986": "Thunderclap Headaches",
        "987": "Thyroid Cancer",
        "988": "Thyroid Nodules",
        "989": "Tinea Versicolor",
        "990": "Tinnitus",
        "991": "Tmj",
        "992": "Toe Walking",
        "993": "Tongue Tie",
        "994": "Tonsil Cancer",
        "995": "Tonsillitis",
        "996": "Tooth Abscess",
        "997": "Torn Meniscus",
        "998": "Tourette Syndrome",
        "999": "Toxic Epidermal Necrolysis",
        "1000": "Toxic Hepatitis",
        "1001": "Toxic Shock Syndrome",
        "1002": "Toxoplasmosis",
        "1003": "Trachoma",
        "1004": "Transient Global Amnesia",
        "1005": "Transient Ischemic Attack",
        "1006": "Transposition Of The Great Arteries",
        "1007": "Transverse Myelitis",
        "1008": "Traumatic Brain Injury",
        "1009": "Travelers Diarrhea",
        "1010": "Trichinosis",
        "1011": "Trichomoniasis",
        "1012": "Trichotillomania",
        "1013": "Tricuspid Atresia",
        "1014": "Tricuspid Valve Regurgitation",
        "1015": "Trigeminal Neuralgia",
        "1016": "Trigger Finger",
        "1017": "Triple X Syndrome",
        "1018": "Truncus Arteriosus",
        "1019": "Tuberculosis",
        "1020": "Tuberous Sclerosis",
        "1021": "Turner Syndrome",
        "1022": "Type 1 Diabetes",
        "1023": "Type 1 Diabetes In Children",
        "1024": "Type 2 Diabetes",
        "1025": "Type 2 Diabetes In Children",
        "1026": "Typhoid",
        "1027": "Typhoid Fever",
        "1028": "Ulcerative Colitis",
        "1029": "Umbilical Hernia",
        "1030": "Undescended Testicle",
        "1031": "Undifferentiated Pleomorphic Sarcoma",
        "1032": "Ureteral Cancer",
        "1033": "Ureteral Obstruction",
        "1034": "Urethral Stricture",
        "1035": "Urinary Tract Infection",
        "1036": "Urine Color",
        "1037": "Uterine Fibroids",
        "1038": "Uterine Polyps",
        "1039": "Uterine Prolapse",
        "1040": "Uveitis",
        "1041": "Vaginal Agenesis",
        "1042": "Vaginal Atrophy",
        "1043": "Vaginal Cancer",
        "1044": "Vaginitis",
        "1045": "Valley Fever",
        "1046": "Varicocele",
        "1047": "Varicose Veins",
        "1048": "Vascular Dementia",
        "1049": "Vasculitis",
        "1050": "Vasovagal Syncope",
        "1051": "Ventricular Fibrillation",
        "1052": "Ventricular Septal Defect",
        "1053": "Ventricular Tachycardia",
        "1054": "Vertebral Tum",
        "1054": "Vertebral Tumor",
        "1055": "Vertigo",
        "1056": "Vesicoureteral Reflux",
        "1057": "Viral Gastroenteritis",
        "1058": "Viral Hemorrhagic Fevers",
        "1059": "Vitamin Deficiency Anemia",
        "1060": "Vitiligo",
        "1061": "Vocal Cord Paralysis",
        "1062": "Von Willebrand Disease",
        "1063": "Vulvar Cancer",
        "1064": "Vulvodynia",
        "1065": "Waldenstrom Macroglobulinemia",
        "1066": "Wet Macular Degeneration",
        "1067": "Wheat Allergy",
        "1068": "Whiplash",
        "1069": "Whipples Disease",
        "1070": "Whooping Cough",
        "1071": "Wilms Tumor",
        "1072": "Wilsons Disease",
        "1073": "Wisdom Teeth",
        "1074": "Wolff Parkinson White Syndrome",
        "1075": "Wrinkles",
        "1076": "Wrist Pain",
        "1077": "X Linked Agammaglobulinemia",
        "1078": "Yeast Infection",
        "1079": "Yips",
        "1080": "Zika Virus",
        "1081": "Zollinger Ellison Syndrome"
    }

    disease = disease_mapping.get(number)

    return disease